'use strict';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const DAY=86400000,HOUR=3600000,FIRST=Date.parse('2026-01-31T00:00:00Z');
const state={page:'overview',scope:'both',horizon:48,day:0,mode:'historical',data:null,busy:false,offline:location.protocol==='file:',request:0,agent:null};
const names={history:'Прогноз и факт',weather:'Погода на площадке',overview:'Обзор прогноза',hourly:'По часам',planner:'Подобрать период',agent:'Работа агента',help:'Как это работает',map:'Карта ветра'};
const finite=n=>typeof n==='number'&&Number.isFinite(n),fmt=(n,d=1)=>finite(n)?n.toLocaleString('ru-RU',{minimumFractionDigits:d,maximumFractionDigits:d}):'—',pct=(n,d=1)=>finite(n)?fmt(n*100,d)+'%':'—';
const dateStr=n=>new Date(FIRST+n*DAY).toISOString().slice(0,10);
const humanDate=(v,opts={})=>new Intl.DateTimeFormat('ru-RU',{timeZone:'Asia/Almaty',day:'2-digit',month:'short',...opts}).format(new Date(v));
const timeStr=v=>humanDate(v,{hour:'2-digit',minute:'2-digit'});
const clockTime=v=>new Intl.DateTimeFormat('ru-RU',{timeZone:'Asia/Almaty',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(v));
const ids=()=>state.scope==='both'?[1,2]:[Number(state.scope)];
const scopeLabel=()=>state.scope==='both'?'Средний уровень двух установок':`Установка ${state.scope}`;
const selectedRows=()=>state.data?state.data.forecast.filter(r=>ids().includes(Number(r.turbine_id))).sort((a,b)=>Date.parse(a.valid_at)-Date.parse(b.valid_at)||a.turbine_id-b.turbine_id):[];
const average=values=>values.length&&values.every(finite)?values.reduce((a,b)=>a+b,0)/values.length:null;
function series(){
 if(!state.data)return [];const times=new Map();
 for(const r of state.data.forecast){if(!times.has(r.valid_at))times.set(r.valid_at,{});times.get(r.valid_at)[r.turbine_id]=r}
 return [...times].sort((a,b)=>Date.parse(a[0])-Date.parse(b[0])).map(([at,units])=>{const chosen=ids().map(id=>units[id]);return {at,units,power:average(chosen.map(r=>r?.power_pred)),wind:average(chosen.map(r=>r?.wind_speed)),temperature:average(chosen.map(r=>r?.temperature))}});
}
let toastTimer,slideTimer,chartGeometry;
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,4500)}
function showPage(page){if(!names[page])return;state.page=page;document.body.classList.toggle('weather-page',page==='weather');document.body.classList.toggle('map-page',page==='map');document.body.classList.toggle('history-page',page==='history');document.querySelectorAll('.page').forEach(p=>p.hidden=p.id!==`page-${page}`);document.querySelectorAll('.nav-item').forEach(b=>{const active=b.dataset.page===page;b.classList.toggle('active',active);if(active)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});$('pageName').textContent=names[page];window.scrollTo({top:0,behavior:'smooth'});if(page==='agent')pollAgent();if(page==='map')openWindMap();if(page==='weather')loadSiteWeather();window.historyView?.onPageChanged(page)}
function openWindMap(){if(location.protocol==='file:')return;const frame=$('windMap');frame.hidden=false;$('mapPlaceholder').hidden=true;if(!frame.getAttribute('src'))frame.src='/map/windy'}
function mapTheme(){const frame=$('windMap');if(frame.getAttribute('src')&&location.protocol!=='file:')frame.contentWindow?.postMessage({type:'windpilot-theme',theme:document.documentElement.dataset.theme},location.origin)}
new MutationObserver(mapTheme).observe(document.documentElement,{attributes:true,attributeFilter:['data-theme']});
function connection(online,detail){$('connection').classList.toggle('online',online);$('connectionText').textContent=online?'Онлайн':'Офлайн';$('connection').title=detail}
function offlineNotice(){ $('dataNotice').hidden=!state.offline;if(state.offline)$('dataNotice').textContent='Автономный просмотр · сохранённые реальные расчёты. Новая погода и автоматический пересчёт доступны через запущенный сервер WindPilot.' }
function setBusy(busy,message='Получаем прогноз…'){state.busy=busy;$('chartLoading').hidden=!busy;$('loadingText').textContent=message;for(const id of ['download','liveButton','recalculate','datePicker','daySlider','previousDay','nextDay','returnHistory'])$(id).disabled=busy;document.querySelectorAll('[data-horizon]').forEach(b=>b.disabled=busy);$('download').disabled=busy||!state.data;$('powerChart').setAttribute('aria-busy',String(busy));if(!busy)syncDate()}
async function api(path,timeout=90000){const c=new AbortController(),timer=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(path,{signal:c.signal});if(!r.ok){const b=await r.json().catch(()=>({}));throw new Error(typeof b.detail==='string'?b.detail:`Ошибка API: ${r.status}`)}return await r.json()}finally{clearTimeout(timer)}}
function validateForecast(data){if(!data||![24,48].includes(data.horizon_hours)||!Array.isArray(data.forecast)||!Number.isFinite(Date.parse(data.forecast_origin)))throw new Error('Сервер вернул неполный прогноз.');for(const id of [1,2]){const rows=data.forecast.filter(r=>Number(r.turbine_id)===id);if(rows.length!==data.horizon_hours||new Set(rows.map(r=>r.valid_at)).size!==rows.length||rows.some(r=>!finite(r.power_pred)||r.power_pred<0||r.power_pred>1||!Number.isFinite(Date.parse(r.valid_at))))throw new Error('В прогнозе отсутствуют часы или есть некорректная мощность.')}return data}
async function loadForecast(refresh=false){if(state.busy)return;const token=++state.request;setBusy(true,refresh?'Проверяем новый выпуск погоды…':'Загружаем прогноз…');$('errorNotice').hidden=true;let result;const key=`${dateStr(state.day)}_${state.horizon}`;
 try{if(location.protocol!=='file:'){try{result=validateForecast(await api(`/forecast?date=${dateStr(state.day+1)}&horizon=${state.horizon}${refresh?'&refresh=true':''}`));state.offline=false}catch(error){if(refresh||!SNAPSHOT.runs[key])throw error;state.offline=true;connection(false,'API недоступен. Показан сохранённый расчёт.')}}
 if(!result){if(refresh)throw new Error('Пересчёт доступен через сервер. В автономном HTML можно просматривать сохранённые результаты.');result=validateForecast(SNAPSHOT.runs[key]);state.offline=true}
 if(token!==state.request)return;state.mode='historical';state.data=result;offlineNotice();render();if(refresh)toast(result.status==='reused'?'Погода проверена. Входы не изменились — сохранён прежний расчёт.':'Получен обновлённый прогноз.');
 }catch(error){if(token!==state.request)return;showError(error,refresh?'Не удалось проверить обновления. Показан последний успешный расчёт.':'Не удалось загрузить прогноз.');if(!refresh){state.data=null;render()}}
 finally{if(token===state.request)setBusy(false)}}
async function loadLive(quiet=false){if(state.busy)return;if(location.protocol==='file:'){toast('Живой прогноз требует запущенного сервера WindPilot. Сейчас открыт автономный HTML.');return}const token=++state.request;setBusy(true,'Получаем текущую погоду и проверяем прогноз…');$('errorNotice').hidden=true;
 try{const result=validateForecast(await api(`/forecast/live?horizon=${state.horizon}`));if(token!==state.request)return;state.data=result;state.mode='live_demo';state.offline=false;connection(true,'Текущий прогноз погоды успешно получен из Open-Meteo.');offlineNotice();render();if(!quiet)showPage('overview');await pollAgent();state.autoSeenRun=state.agent?.last_run_id}
 catch(error){if(token!==state.request)return;showError(error,'Живой прогноз недоступен. Показан последний успешный расчёт, если он есть.');connection(false,'Не удалось завершить текущий погодный запрос.');if(state.data){state.horizon=state.data.horizon_hours;render()}}
 finally{if(token===state.request)setBusy(false)}}
function showError(error,prefix){$('errorNotice').textContent=prefix+' '+(error.name==='AbortError'?'Погодный источник не ответил вовремя. Повторите запрос позже.':error.message);$('errorNotice').hidden=false}
function render(){const d=state.data,live=state.mode==='live_demo';$('horizonTitle').textContent=state.horizon===24?'24 часа':'48 часов';$('originLabel').textContent=d?humanDate(d.forecast_origin,{year:'numeric',hour:'2-digit',minute:'2-digit'})+' · UTC+5':'Прогноз не загружен';$('modeLabel').textContent=live?'ДЕМОНСТРАЦИЯ · СЕГОДНЯ':'ИСТОРИЯ ПРОГНОЗОВ';$('liveNotice').hidden=!live;$('timelineCard').hidden=live;$('scopeSelect').value=state.scope;document.querySelectorAll('[data-horizon]').forEach(b=>{const active=Number(b.dataset.horizon)===state.horizon;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});
 const issue=d?.forecast.find(r=>r.weather_issued_at)?.weather_issued_at;$('weatherBadge').hidden=!issue;if(issue)$('weatherBadge').textContent=`Выпуск ${timeStr(issue)} · за ${fmt((Date.parse(d.forecast_origin)-Date.parse(issue))/HOUR,0)} ч до запуска`;
 renderSummary();renderChart();renderHourly();renderPlanner();renderAgent();$('download').disabled=!d||state.busy;window.historyView?.syncModes();
}
function renderSummary(){const rows=series().filter(r=>finite(r.power));$('scopeCaption').textContent=state.scope==='both'?'Средняя доля максимальной мощности двух установок.':'Доля максимальной мощности выбранной установки.';$('chartSubtitle').textContent=scopeLabel()+', %';
 if(!rows.length){for(const id of ['meanValue','peakValue','lowValue','windValue'])$(id).textContent='—';for(const id of ['unitMeans','peakCaption','lowCaption'])$(id).textContent='';$('insightTitle').textContent='Расчёт не загружен';$('insightText').textContent='Выберите дату и получите прогноз.';return}
 $('meanValue').innerHTML=fmt(average(rows.map(r=>r.power))*100)+'<small>%</small>';
 $('unitMeans').innerHTML=ids().map(id=>`<span>Установка ${id} <b>${pct(average(rows.map(r=>r.units[id]?.power_pred)))}</b></span>`).join('');
 const high=rows.reduce((a,b)=>a.power>=b.power?a:b),low=rows.reduce((a,b)=>a.power<=b.power?a:b);$('peakValue').textContent=pct(high.power);$('peakCaption').textContent=timeStr(high.at);$('lowValue').textContent=pct(low.power);$('lowCaption').textContent=timeStr(low.at);
 const wind=average(rows.map(r=>r.wind));$('windValue').textContent=finite(wind)?fmt(wind)+' м/с':'Нет данных';
 $('insightTitle').textContent=`Наибольший уровень — ${timeStr(high.at)}`;$('insightText').textContent=`В выбранном горизонте ожидается от ${pct(low.power,0)} до ${pct(high.power,0)}. Средний уровень — ${pct(average(rows.map(r=>r.power)),0)}. Для периода с нужной выработкой используйте подбор по часам.`;
}
function freshBaseline(){if(!state.data||state.mode==='live_demo')return null;const known=ids().map(id=>(state.data.baseline||[]).find(b=>Number(b.turbine_id)===id));return known.every(b=>b&&finite(b.age_hours)&&b.age_hours>=0&&b.age_hours<=3)?{value:average(known.map(b=>b.value)),at:known[0].observed_at}:null}
function renderChart(){const svg=$('powerChart'),rows=series(),data=state.data;$('chartTooltip').hidden=true;if(!data||!rows.length){svg.innerHTML='<text x="550" y="155" text-anchor="middle">Прогноз появится после загрузки</text>';$('chartLegend').innerHTML='';$('baselineCaption').textContent='';chartGeometry=null;return}
 const L=55,R=1070,T=40,B=258,W=1100,origin=Date.parse(data.forecast_origin),last=Date.parse(rows.at(-1).at),x=v=>L+(Date.parse(v)-origin)/(last-origin)*(R-L),y=p=>B-p*(B-T);let html='';
 for(const p of [0,.25,.5,.75,1]){html+=`<line x1="${L}" y1="${y(p)}" x2="${R}" y2="${y(p)}" stroke="var(--grid)" stroke-dasharray="3 5"/><text x="${L-12}" y="${y(p)+4}" text-anchor="end">${p*100}%</text>`}
 const ticks=state.horizon===24?[0,4,8,12,16,20,24]:[0,6,12,18,24,30,36,42,48];for(const h of ticks){const t=h===state.horizon?last:origin+h*HOUR,xx=L+(t-origin)/(last-origin)*(R-L),anchor=h===0?'start':h===state.horizon?'end':'middle';html+=`<text x="${xx}" y="${B+25}" text-anchor="${anchor}">${clockTime(t)}</text>`;if(h%12===0)html+=`<text x="${xx}" y="${B+44}" text-anchor="${anchor}" style="font-size:10px">${humanDate(t)}</text>`}
 html+=`<line x1="${L}" y1="${T-7}" x2="${L}" y2="${B}" stroke="var(--chart-two)" stroke-dasharray="4 4"/><text x="${L+6}" y="19" style="font-size:9px;fill:var(--accent)">${state.mode==='live_demo'?'МОМЕНТ ЖИВОГО ПРОГНОЗА':'МОМЕНТ ПРОГНОЗА'}</text>`;
 const base=freshBaseline();if(base)html+=`<line x1="${L}" y1="${y(base.value)}" x2="${R}" y2="${y(base.value)}" stroke="var(--chart-two)" stroke-width="1.7" stroke-dasharray="6 6"/>`;
 const path=rows.map((r,i)=>`${i?'L':'M'}${x(r.at).toFixed(2)},${y(r.power).toFixed(2)}`).join(' ');html+=`<path d="${path}" stroke="var(--chart-one)" stroke-width="3" stroke-linecap="round" stroke-linejoin="round" fill="none"/><g id="hoverLayer"></g>`;svg.innerHTML=html;
 $('chartLegend').innerHTML=`<span><i></i>${esc(scopeLabel())}</span>`+(base?'<span><i class="dashed"></i>Наивный бейзлайн · последнее известное</span>':'');$('baselineCaption').textContent=base?`Последнее известное измерение: ${timeStr(base.at)}.`:'Бейзлайн не показан: нет свежих фактических измерений мощности.';chartGeometry={L,R,T,B,W,x,y,rows};
}
function hoverChart(clientX,keyboardIndex){if(!chartGeometry)return;const g=chartGeometry,rect=$('powerChart').getBoundingClientRect(),px=(clientX-rect.left)/(rect.width||g.W)*g.W;let i=keyboardIndex??g.rows.reduce((best,r,j)=>Math.abs(g.x(r.at)-px)<Math.abs(g.x(g.rows[best].at)-px)?j:best,0);i=Math.max(0,Math.min(g.rows.length-1,i));$('powerChart').dataset.index=i;const row=g.rows[i],x=g.x(row.at);$('hoverLayer').innerHTML=`<line x1="${x}" y1="${g.T}" x2="${x}" y2="${g.B}" stroke="var(--chart-two)" stroke-dasharray="3 4"/><circle cx="${x}" cy="${g.y(row.power)}" r="4" fill="var(--card-bg)" stroke="var(--chart-one)" stroke-width="2"/>`;
 const tip=$('chartTooltip');tip.innerHTML=`<strong>${timeStr(row.at)}</strong><div class="tooltip-row"><span>${state.scope==='both'?'Средний уровень':'Прогноз'}</span><b>${pct(row.power)}</b></div>`+ids().map(id=>`<div class="tooltip-row"><span>Установка ${id}</span><span>${pct(row.units[id]?.power_pred)}</span></div>`).join('');tip.hidden=false;tip.style.left=Math.min((rect.width||g.W)-205,Math.max(15,x/g.W*(rect.width||g.W)+12))+'px';tip.style.top='40px';
}
function renderHourly(){const rows=series();$('hourlyPowerTitle').textContent=state.scope==='both'?'Средний уровень':`Установка ${state.scope}`;$('hourlyTable').innerHTML=rows.length?rows.map(r=>`<tr><td>${timeStr(r.at)}</td><td><span class="power-cell"><span class="power-bar"><i style="width:${r.power*100}%"></i></span>${pct(r.power)}</span></td><td>${pct(r.units[1]?.power_pred)}</td><td>${pct(r.units[2]?.power_pred)}</td><td>${fmt(r.wind)}</td><td>${finite(r.temperature)?fmt(r.temperature)+' °C':'—'}</td></tr>`).join(''):'<tr><td colspan="6" class="empty-state">Сначала загрузите прогноз.</td></tr>'}
function planningWindows(rows,duration,threshold,quiet){const windows=[];for(let i=0;i<=rows.length-duration;i++){const window=rows.slice(i,i+duration);if(window.some((r,k)=>!finite(r.power)||(k>0&&Date.parse(r.at)-Date.parse(window[k-1].at)!==HOUR)))continue;if(quiet||window.every(r=>r.power>=threshold))windows.push({start:i,end:i+duration-1,mean:average(window.map(r=>r.power)),min:Math.min(...window.map(r=>r.power))})}return quiet?windows.sort((a,b)=>a.mean-b.mean||a.start-b.start):windows}
function renderPlanner(){const rows=series(),duration=Number($('duration').value),threshold=Number($('threshold').value)/100,quiet=$('planMode').value==='quiet';$('thresholdValue').textContent=pct(threshold,0);$('thresholdField').hidden=quiet;$('plannerScope').textContent=scopeLabel()+` · ${state.horizon} часов · ${state.mode==='live_demo'?'демонстрационный текущий прогноз':'выбранный исторический прогноз'}`;const windows=planningWindows(rows,duration,threshold,quiet),best=windows[0];
 $('hourStrip').innerHTML=rows.map((r,i)=>`<span style="--level:${r.power}" class="${!quiet&&r.power>=threshold?'match':''} ${best&&i>=best.start&&i<=best.end?'chosen':''}" title="${timeStr(r.at)} · ${pct(r.power)}"></span>`).join('');$('stripLabels').innerHTML=rows.length?`<span>${timeStr(rows[0].at)}</span><span>Каждая полоска — 1 час</span><span>${timeStr(rows.at(-1).at)}</span>`:'';
 if(!rows.length){$('plannerResult').innerHTML='<p>Сначала загрузите прогноз.</p>';return}if(!best){$('plannerResult').innerHTML=`<span class="eyebrow">ПОДХОДЯЩЕГО ПЕРИОДА НЕТ</span><h2>Условие не выполняется</h2><p>В этих ${state.horizon} часах нет ${duration} часов подряд с уровнем не ниже ${pct(threshold,0)}. Попробуйте меньший порог или длительность.</p>`;return}
 const range=w=>`${timeStr(rows[w.start].at)} — ${timeStr(Date.parse(rows[w.end].at)+HOUR)}`;
 $('plannerResult').innerHTML=`<span class="eyebrow">${quiet?'САМЫЙ НИЗКИЙ СРЕДНИЙ УРОВЕНЬ':'ПЕРВЫЙ ПОДХОДЯЩИЙ ПЕРИОД'}</span><h2>${range(best)}</h2><p>${duration} ч подряд · средний уровень ${pct(best.mean)}${quiet?'':` · не ниже ${pct(best.min)} в каждом часу`}.</p>`;
 const alternatives=windows.filter(w=>w.start>best.end||w.end<best.start).filter((w,i,arr)=>i===0||w.start>=arr[i-1].start+duration).slice(0,2);if(!quiet&&alternatives.length)$('plannerResult').innerHTML+='<div class="window-list">'+alternatives.map(w=>`<span class="window-option">Ещё: ${range(w)}</span>`).join('')+'</div>';
}
function renderAgent(){const d=state.data;if(!d){$('agentStatus').textContent='Нет загруженного расчёта';$('agentDuration').textContent='—';$('agentSteps').innerHTML='<div class="empty-state">Получите прогноз, чтобы увидеть журнал.</div>';$('agentDetails').innerHTML='';renderAuto();return}const reused=d.status==='reused',a=d.analysis||{},trace=d.trace||[],first=d.forecast[0]||{},event=n=>trace.find(e=>e.event===n);
 $('agentStatus').textContent=reused?'Входы не изменились · расчёт сохранён':'Расчёт выполнен';$('agentDuration').textContent=finite(d.request_duration_ms)?fmt(d.request_duration_ms/1000,2)+' сек':'Не записано';
 const stages=[
 {title:'Получил погоду',event:event('weather_validated'),body:`Open-Meteo: ветер и температура по координатам двух установок. ${state.mode==='live_demo'?'Текущий прогноз погоды.':'Архивный выпуск погоды.'}`,meta:first.weather_issued_at?'Выпуск: '+timeStr(first.weather_issued_at)+' UTC+5.':'Время выпуска не сообщается текущим API; возраст выпуска не вычисляется.'},
 {title:'Подготовил данные',event:event('features_prepared'),body:reused?'Новая подготовка не нужна: проверенные погодные входы не изменились.':'Погодные входы подготовлены для почасового расчёта двух установок.',meta:'Пропусков в погодных входах: '+(a.missing_weather_values??'не указано'),skip:reused},
 {title:'Запустил модель',event:event('turbine_model_started')||event('model_started'),body:reused?'Повторный запуск не выполнялся. Использован результат на тех же входах.':'Отдельная модель каждой установки рассчитала относительную мощность.',meta:'Версия: '+(first.model_version||a.model_version||'не указана').slice(0,16),skip:reused},
 {title:'Сформировал почасовой прогноз',event:event('forecast_formed')||event('completed'),body:`${d.horizon_hours} часов для каждой установки · ${d.forecast.length} отдельных значений.`,meta:'Диапазон модели 0–1 отображается в интерфейсе как 0–100%.',skip:reused},
 {title:'Проверил результат',event:event('analysis_completed'),body:`Проверены пропуски и диапазон 0–1. Ограничено до допустимого диапазона: ${a.clipped_prediction_count??'не указано'} значений.`,meta:reused?'Показана сохранённая проверка.':a.previous_run_id?`Среднее абсолютное изменение по совпадающим часам: ${fmt(a.mean_absolute_change*100,2)} п.п.`:'Предыдущей версии для сравнения нет.',skip:reused},
 {title:'Проверяет обновления и пересчитывает',event:event('unchanged_inputs_reused'),body:reused?'При этой проверке входы не изменились. Существующий прогноз сохранён.':'При изменении погодных входов создаётся новая версия расчёта.',meta:state.mode==='live_demo'?'Текущее состояние автоматических проверок указано выше.':'Исторический прогноз не меняется сам: кнопка выше повторно проверяет архив. Автоматический цикл работает с текущей погодой.',pending:!reused}
 ];
 $('agentSteps').innerHTML=stages.map(s=>`<div class="step ${s.pending?'pending':''}"><span class="step-dot"></span><div class="step-time">${s.event?clockTime(s.event.at):s.skip?'Из сохранённого':s.pending?'Ожидание':'Время не записано'}<small>${s.event?humanDate(s.event.at)+' · UTC+5':''}</small></div><div><h3>${s.title}</h3><p>${esc(s.body)}</p><div class="step-meta">${esc(s.meta)}</div></div></div>`).join('');
 $('agentDetails').innerHTML=[['ID расчёта',d.run_id],['Версия модели',first.model_version||a.model_version],['Момент прогноза',d.forecast_origin],['Источник',first.weather_source],['Получено погодных значений',d.forecast.length],['Режим',state.mode==='live_demo'?'Демонстрационный, текущая погода':'Исторический']].map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v??'Не указано')}</dd>`).join('');renderAuto();
}
function renderAuto(){const a=state.agent;if(location.protocol==='file:'||!a){$('autoTitle').textContent='Автообновление недоступно';$('autoText').textContent='Статус сервера не получен. В автономном HTML новые расчёты не запускаются.';return}if(!a.enabled){$('autoTitle').textContent='Автообновление отключено на сервере';$('autoText').textContent='Ручная проверка доступна кнопкой выше.';return}$('autoTitle').textContent=a.status==='running'?'Агент проверяет текущую погоду':a.status==='error'?'Не удалось проверить текущую погоду':`Проверка каждые ${fmt(a.interval_seconds/60,0)} минут`;$('autoText').textContent=(a.last_checked_at?`Последняя проверка: ${timeStr(a.last_checked_at)}. `:'Первый цикл ещё не завершён. ')+(a.next_check_at?`Следующая: ${clockTime(a.next_check_at)}. `:'')+(a.status==='error'?'':a.last_result==='reused'?'Входы не изменились. ':a.last_result==='created'?'Создан новый прогноз. ':'')+(a.error?'Ошибка источника: '+a.error:'Работает на сервере, пока сервис запущен.');}
async function pollAgent(){if(location.protocol==='file:')return;try{state.agent=await api('/agent/status',8000);renderAuto()}catch(_){state.agent=null;renderAuto()}}
function syncDate(){$('datePicker').value=dateStr(state.day);$('daySlider').value=state.day;$('daySlider').setAttribute('aria-valuetext',humanDate(dateStr(state.day)+'T12:00:00+05:00'));$('previousDay').disabled=state.busy||state.day===0;$('nextDay').disabled=state.busy||state.day===28}
function setDay(n,load=true){if(!Number.isFinite(n))return;state.day=Math.max(0,Math.min(28,n));syncDate();if(load)loadForecast()}
function downloadCSV(){if(!state.data)return;const fields=['run_id','turbine_id','forecast_origin','valid_at','power_pred','weather_source','weather_issued_at','model_version'];const cell=v=>'"'+String(v??'').replaceAll('"','""')+'"';const csv='\ufeff'+[fields.join(','),...selectedRows().map(r=>fields.map(f=>cell(r[f])).join(','))].join('\r\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`windpilot_${state.data.run_id}_${state.scope}_${state.horizon}h.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('CSV сохранён. Мощность в файле — на шкале 0–1.')}
function applyTheme(theme,persist=false){const dark=theme==='dark';document.documentElement.dataset.theme=dark?'dark':'light';const label=dark?'Включить светлую тему':'Включить тёмную тему';$('themeToggle').setAttribute('aria-label',label);$('themeToggle').setAttribute('aria-pressed',String(dark));$('themeToggle').title=label;$('themeIcon').setAttribute('href',dark?'#i-sun':'#i-moon');document.querySelector('meta[name=theme-color]').content=dark?'#111b28':'#f3f6fa';if(persist)try{localStorage.setItem('windpilot-theme',dark?'dark':'light')}catch(_){}}
document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();showPage(b.dataset.page)}));
$('scopeSelect').addEventListener('change',e=>{state.scope=e.target.value;render()});document.querySelectorAll('[data-horizon]').forEach(b=>b.addEventListener('click',()=>{if(state.busy)return;state.horizon=Number(b.dataset.horizon);state.mode==='live_demo'?loadLive(true):loadForecast()}));
$('daySlider').addEventListener('input',e=>{clearTimeout(slideTimer);setDay(Number(e.target.value),false);slideTimer=setTimeout(loadForecast,220)});$('daySlider').addEventListener('change',()=>{clearTimeout(slideTimer);setDay(Number($('daySlider').value))});$('datePicker').addEventListener('change',e=>{if(!e.target.value||!e.target.validity.valid){toast($('calendarHint').textContent);syncDate();return}setDay(Math.round((Date.parse(e.target.value+'T00:00:00Z')-FIRST)/DAY))});$('previousDay').addEventListener('click',()=>setDay(state.day-1));$('nextDay').addEventListener('click',()=>setDay(state.day+1));$('download').addEventListener('click',downloadCSV);$('liveButton').addEventListener('click',()=>loadLive());$('returnHistory').addEventListener('click',()=>loadForecast());$('recalculate').addEventListener('click',()=>state.mode==='live_demo'?loadLive(true):loadForecast(true));$('themeToggle').addEventListener('click',()=>applyTheme(document.documentElement.dataset.theme==='dark'?'light':'dark',true));
for(const id of ['planMode','threshold','duration'])$(id).addEventListener('input',renderPlanner);
$('powerChart').addEventListener('pointermove',e=>hoverChart(e.clientX));$('powerChart').addEventListener('pointerleave',()=>{$('chartTooltip').hidden=true;if($('hoverLayer'))$('hoverLayer').innerHTML=''});$('powerChart').addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();hoverChart(0,Number($('powerChart').dataset.index||0)+(e.key==='ArrowRight'?1:-1))}});
async function init(){applyTheme(document.documentElement.dataset.theme);syncDate();await loadForecast();const initialPage=location.hash.slice(1);if(names[initialPage])showPage(initialPage);if(location.protocol!=='file:'){pollAgent();api('/weather/status',10000).then(s=>connection(s.status==='online',`Погодный источник проверен ${timeStr(s.checked_at)}.`)).catch(()=>connection(false,'Доступ к погоде не подтверждён.'));setInterval(async()=>{if(document.hidden)return;await pollAgent();if(state.mode==='live_demo'&&state.agent?.last_run_id&&state.agent.last_run_id!==state.autoSeenRun&&!state.busy)loadLive(true)},60000)}}
init();
