/* Historical observations and honest, out-of-sample reconstructions. */
(() => {
 'use strict';
 const HOUR_MS=3600000,DAY_MS=24*HOUR_MS;
 const isNumber=n=>typeof n==='number'&&Number.isFinite(n);
 function dateOnly(value){if(!/^\d{4}-\d{2}-\d{2}$/.test(value))return null;const t=Date.parse(value+'T00:00:00Z');return Number.isFinite(t)&&new Date(t).toISOString().slice(0,10)===value?t:null}
 function validateRange(start,end){const a=dateOnly(start),b=dateOnly(end);if(a===null||b===null)throw new Error('Выберите корректные даты начала и конца.');if(b<a)throw new Error('Конец периода должен быть не раньше начала.');const days=(b-a)/DAY_MS+1;if(days>31)throw new Error('Выберите не больше 31 дня за один раз.');return days}
 function stationMidnight(date){const target=dateOnly(date);let instant=target;const formatter=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Almaty',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'});for(let i=0;i<3;i++){const p=Object.fromEntries(formatter.formatToParts(instant).map(x=>[x.type,x.value]));const local=Date.UTC(+p.year,+p.month-1,+p.day,+p.hour,+p.minute,+p.second);const delta=target-local;if(!delta)return instant;instant+=delta}return instant}
 function validatePayload(data,start,end){
  const days=validateRange(start,end);if(!data||!Array.isArray(data.rows)||data.start!==start||data.end!==end||data.timezone!=='Asia/Almaty')throw new Error('Сервер вернул историю для другого периода или неполный ответ.');
  const first=stationMidnight(start),nextDay=new Date(dateOnly(end)+DAY_MS).toISOString().slice(0,10),last=stationMidnight(nextDay),seen=new Set();
  for(const row of data.rows){const t=Date.parse(row.valid_at),id=Number(row.turbine_id),key=t+'_'+id;
   if(![1,2].includes(id)||!Number.isFinite(t)||t<first||t>=last||(t-first)%HOUR_MS||seen.has(key))throw new Error('В истории есть неверные или повторяющиеся часы.');seen.add(key);
   for(const field of ['power_actual','power_pred','wind_speed_actual','temperature_actual'])if(row[field]!==null&&!isNumber(row[field]))throw new Error('Некорректные значения в истории. Пропуски должны быть явно обозначены.');
   if(row.power_pred!==null&&(row.power_pred<0||row.power_pred>1))throw new Error('Прогноз вне диапазона 0–1.');
  }
  if(seen.size!==(last-first)/HOUR_MS*2)throw new Error('Не все часы присутствуют в истории. Пропуски должны быть явно обозначены.');
  return data;
 }
 function aggregate(rows,scope){const ids=scope==='both'?[1,2]:[Number(scope)],times=new Map();for(const row of rows){if(!times.has(row.valid_at))times.set(row.valid_at,{});times.get(row.valid_at)[Number(row.turbine_id)]=row}
  return [...times].sort((a,b)=>Date.parse(a[0])-Date.parse(b[0])).map(([at,units])=>{const avg=field=>{const values=ids.map(id=>units[id]?.[field]);return values.every(isNumber)?values.reduce((a,b)=>a+b,0)/ids.length:null},actual=avg('power_actual'),predicted=avg('power_pred');return{at,actual,predicted,deviation:isNumber(actual)&&isNumber(predicted)?(predicted-actual)*100:null,wind:avg('wind_speed_actual'),temperature:avg('temperature_actual'),units}});
 }
 function lineSegments(rows,field,x,y){let path='',previous=null;for(const r of rows){const at=Date.parse(r.at);if(!isNumber(r[field])){previous=null;continue}path+=(previous!==null&&at-previous===HOUR_MS?'L':'M')+x(at).toFixed(2)+' '+y(r[field]).toFixed(2)+' ';previous=at}return path.trim()}
 const csvFields=['turbine_id','valid_at','power_actual','power_pred','deviation_pp','forecast_origin','model_version','forecast_kind','wind_speed_actual','temperature_actual','wind_speed_forecast','temperature_forecast','weather_issued_at','weather_available_at','weather_selection_reason'];
 function toCSV(rows,scope){const quote=v=>'"'+String(v??'').replaceAll('"','""')+'"',selected=rows.filter(r=>scope==='both'||Number(r.turbine_id)===Number(scope)).sort((a,b)=>Date.parse(a.valid_at)-Date.parse(b.valid_at)||a.turbine_id-b.turbine_id);return '\ufeff'+[csvFields.join(','),...selected.map(r=>csvFields.map(k=>quote(k==='deviation_pp'?(isNumber(r.power_pred)&&isNumber(r.power_actual)?(r.power_pred-r.power_actual)*100:null):r[k])).join(','))].join('\r\n')}
 const helpers={validateRange,validatePayload,aggregate,lineSegments,toCSV,stationMidnight};
 if(typeof module!=='undefined'&&module.exports){module.exports=helpers;return}
 const local={kind:'compare',data:null,availability:null,request:0,controller:null,loading:false};
 const element=id=>document.getElementById(id),safe=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const number=(v,d=1)=>isNumber(v)?v.toLocaleString('ru-RU',{maximumFractionDigits:d,minimumFractionDigits:d}):'—';
 const percent=v=>isNumber(v)?number(v*100)+'%':'—';
 const dateTime=v=>Number.isFinite(Date.parse(v))?new Intl.DateTimeFormat('ru-RU',{timeZone:'Asia/Almaty',day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(v)):'Не сообщается';
 const simpleDate=v=>Number.isFinite(Date.parse(v))?new Intl.DateTimeFormat('ru-RU',{timeZone:'Asia/Almaty',day:'2-digit',month:'short',year:'numeric'}).format(new Date(v+'T12:00:00+05:00')):v;
 const periodLabels={january_validation:'Отложенная проверка января',retrospective:'Отдельная ретроспектива',historical_replay:'Воспроизведение архива',saved_live:'Сохранённый живой расчёт'};
 function syncModes(){const history=state.page==='history';for(const [id,active] of [['modeToday',!history&&state.mode==='live_demo'&&['overview','hourly','planner','agent'].includes(state.page)],['modeCompare',history&&local.kind==='compare'],['modeHistory',history&&local.kind==='history']]){element(id).classList.toggle('active',active);element(id).setAttribute('aria-pressed',String(active))}}
 function heading(){element('historyTitle').textContent=local.kind==='compare'?'Что ожидали. Что получили.':'История вашей площадки.';element('historyIntro').textContent=local.kind==='compare'?'Почасовой расчёт рядом с измеренной мощностью — без подмены отсутствующих данных.':'Выберите до 31 дня. Покажем доступные измерения, сохранённые расчёты и явные пропуски.';element('pageName').textContent=local.kind==='compare'?'Прогноз и факт':'История данных';syncModes()}
 function setError(message){element('historyError').textContent=message;element('historyError').hidden=false}
 function renderAvailability(){const data=local.data||local.availability;if(!data)return;const periods=data.forecast_periods||local.availability?.forecast_periods||[];element('historyProvenance').innerHTML=periods.length?'<ul>'+periods.map(p=>`<li><b>${safe(simpleDate(p.start))} — ${safe(simpleDate(p.end))}</b><br>${safe(p.label||periodLabels[p.forecast_kind]||p.forecast_kind)}${p.model_version?`<br><span class="small muted">Версия: ${safe(p.model_version)}</span>`:''}</li>`).join('')+'</ul>':'<p>Сохранённые периоды прогноза не сообщены сервером.</p>';element('historyLatest').disabled=!data.observed_end}
 async function availability(){if(local.availability||location.protocol==='file:')return;try{local.availability=await api('/history/availability',15000);renderAvailability()}catch(_){/* Main history response still carries bounds and notices. */}}
 function rows(){return local.data?aggregate(local.data.rows,element('historyScope').value):[]}
 function renderChart(series){const svg=element('historyChart'),L=60,R=1070,T=22,B=252,min=Date.parse(series[0]?.at),max=Date.parse(series.at(-1)?.at),x=t=>L+(t-min)/Math.max(HOUR_MS,max-min)*(R-L),y=v=>B-v*(B-T);let html='<title>Фактическая и прогнозная относительная мощность по часам</title><desc>Пропуски показаны разрывами. Полные значения доступны в таблице под графиком.</desc>';
  for(const v of [0,.25,.5,.75,1])html+=`<line x1="${L}" x2="${R}" y1="${y(v)}" y2="${y(v)}" stroke="var(--grid)" stroke-dasharray="3 5"/><text x="${L-12}" y="${y(v)+4}" text-anchor="end">${v*100}%</text>`;
  const step=Math.max(1,Math.ceil((series.length-1)/6)),tickIndices=[...new Set([...series.map((_,i)=>i).filter(i=>i%step===0),series.length-1])];
  for(const i of tickIndices){const r=series[i];if(!r)continue;const t=Date.parse(r.at),date=new Intl.DateTimeFormat('ru-RU',{timeZone:'Asia/Almaty',day:'2-digit',month:'short'}).format(new Date(t)),hour=new Intl.DateTimeFormat('ru-RU',{timeZone:'Asia/Almaty',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(t));html+=`<text x="${x(t)}" y="278" text-anchor="middle">${date}</text><text x="${x(t)}" y="296" text-anchor="middle">${hour}</text>`}
  for(const [field,color,dash] of [['actual','var(--text)',''],['predicted','var(--chart-one)','6 3']]){const d=lineSegments(series,field,x,y);if(d)html+=`<path class="history-line-${field}" d="${d}" fill="none" stroke="${color}" stroke-width="2" stroke-dasharray="${dash}" vector-effect="non-scaling-stroke"/>`;for(let i=0;i<series.length;i++){const row=series[i];if(isNumber(row[field])&&!isNumber(series[i-1]?.[field])&&!isNumber(series[i+1]?.[field]))html+=`<circle cx="${x(Date.parse(row.at))}" cy="${y(row[field])}" r="3" fill="${color}"/>`}}
  if(!series.some(r=>isNumber(r.actual)||isNumber(r.predicted)))html+='<text x="565" y="145" text-anchor="middle">За этот период нет измерений и сохранённых прогнозов</text>';
  svg.innerHTML=html;
 }
 function render(){if(!local.data)return;const data=local.data,series=rows(),scope=element('historyScope').value,paired=series.filter(r=>isNumber(r.actual)&&isNumber(r.predicted)).length,missing=series.filter(r=>!isNumber(r.actual)).length;
  element('historyObservedEnd').textContent=data.observed_end?dateTime(data.observed_end):'Измерений нет';element('historyPaired').textContent=paired.toLocaleString('ru-RU')+' / '+series.length.toLocaleString('ru-RU');element('historyMissing').textContent=missing.toLocaleString('ru-RU')+' ч';element('historyScopeNote').textContent=scope==='both'?'Сравнение при наличии обеих установок':`Установка ${scope}`;
  element('historyChartSubtitle').textContent=`${simpleDate(data.start)} — ${simpleDate(data.end)} · ${scope==='both'?'среднее двух установок':`установка ${scope}`}, %`;
  const notices=(data.notices||[]).map(n=>typeof n==='string'?n:n.message).filter(Boolean);if(!series.some(r=>isNumber(r.actual)))notices.push('Фактические данные за выбранный период не загружены. Сравнить прогноз с выработкой пока нельзя.');if(!series.some(r=>isNumber(r.predicted)))notices.push('Сохранённого прогноза за выбранный период нет. Линия прогноза не строится.');
  element('historyNotices').innerHTML=[...new Set(notices)].map(n=>`<div class="notice"><span>${safe(n)}</span></div>`).join('');
  element('historyChartNote').textContent='Проценты соответствуют шкале модели 0–1. Это не МВт и не вероятность. '+(scope==='both'?'Среднее рассчитано только для часов, где есть данные обеих установок. ':'')+'Пропуски не соединяются линией.';
  renderChart(series);element('historyTable').innerHTML=series.map(r=>`<tr><td>${safe(dateTime(r.at))}</td><td>${percent(r.actual)}</td><td class="history-prediction">${percent(r.predicted)}</td><td>${isNumber(r.deviation)?(r.deviation>0?'+':'')+number(r.deviation):'—'}</td><td>${number(r.wind)}</td><td>${number(r.temperature)}</td></tr>`).join('');
  element('historyContent').hidden=false;element('historyDownload').disabled=local.loading;renderAvailability();
 }
 async function load(){const start=element('historyStart').value,end=element('historyEnd').value;local.controller?.abort();const request=++local.request;local.loading=false;local.data=null;element('historyContent').hidden=true;element('historyLoading').hidden=true;element('historyLoad').disabled=false;element('historyError').hidden=true;
  try{validateRange(start,end)}catch(e){setError(e.message);return}if(location.protocol==='file:'){setError('История измерений доступна через сервер WindPilot. Автономный HTML содержит только сохранённые февральские прогнозы.');return}
  const controller=new AbortController();local.controller=controller;local.loading=true;element('historyLoading').hidden=false;element('historyLoad').disabled=true;element('historyChart').setAttribute('aria-busy','true');const timer=setTimeout(()=>controller.abort(),60000);
  try{const response=await fetch(`/history?start=${encodeURIComponent(start)}&end=${encodeURIComponent(end)}`,{signal:controller.signal});if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(typeof body.detail==='string'?body.detail:`Не удалось получить историю (HTTP ${response.status}).`)}const data=validatePayload(await response.json(),start,end);if(request!==local.request)return;local.data=data;render();availability()}
  catch(e){if(request!==local.request)return;setError(e.name==='AbortError'?'Сервер не ответил вовремя. Повторите загрузку периода.':e.message)}
  finally{clearTimeout(timer);if(request===local.request){local.loading=false;element('historyLoad').disabled=false;element('historyLoading').hidden=true;element('historyDownload').disabled=!local.data;element('historyChart').setAttribute('aria-busy','false')}}
 }
 function pick(start,end){element('historyStart').value=start;element('historyEnd').value=end;return load()}
 function invalidate(){if(!local.loading&&!local.data)return;local.controller?.abort();++local.request;local.loading=false;local.data=null;element('historyContent').hidden=true;element('historyLoading').hidden=true;element('historyLoad').disabled=false;element('historyError').hidden=true}
 function open(kind){local.kind=kind;showPage('history');heading()}
 window.historyView={syncModes,onPageChanged(page){syncModes();if(page==='history'){heading();if(!local.data&&!local.loading)load()}},open};
 element('historyForm').addEventListener('submit',e=>{e.preventDefault();load()});element('historyScope').addEventListener('change',render);for(const id of ['historyStart','historyEnd'])element(id).addEventListener('input',invalidate);
 document.querySelectorAll('[data-history-period]').forEach(button=>button.addEventListener('click',()=>{const month=button.dataset.historyPeriod;pick(month+'-01',month+'-'+(month==='2026-02'?'28':'31'))}));
 element('historyLatest').addEventListener('click',async()=>{await availability();const end=(local.availability?.observed_end||local.data?.observed_end||'').slice(0,10);if(!end){setError('Последняя дата измерений не получена. Укажите период вручную.');return}const start=new Date(dateOnly(end)-6*DAY_MS).toISOString().slice(0,10);local.kind='history';heading();pick(start,end)});
 element('modeToday').addEventListener('click',()=>{showPage('overview');loadLive()});element('modeCompare').addEventListener('click',()=>open('compare'));element('modeHistory').addEventListener('click',()=>open('history'));
 element('historyDownload').addEventListener('click',()=>{if(!local.data)return;const scope=element('historyScope').value,blob=new Blob([toCSV(local.data.rows,scope)],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`windpilot_history_${local.data.start}_${local.data.end}_${scope}.csv`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('CSV сохранён. Мощность — на шкале 0–1, отклонение — в процентных пунктах; пропуски пустые.')});
 syncModes();
})();
